### ISSUE TITLE
Breaks when validating lists?

### ISSUE THREAD

**Issue by chanon** [bobfp/skooma#10]
Please see:
```
iex(15)> Skooma.valid?(24, [:list, :string])
** (Protocol.UndefinedError) protocol Enumerable not implemented for 24. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /root/deb/elixir_1.8.1-2/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /root/deb/elixir_1.8.1-2/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.map_reduce/3
    (elixir) lib/enum.ex:2749: Enum.with_index/2
    (skooma) lib/skooma.ex:74: Skooma.validate_list/3
    (skooma) lib/skooma.ex:12: Skooma.valid?/3
```
I think this should return an :error tuple with a reason.

This also causes `:union` schemas with lists to break even though the data is valid

```
iex(15)> Skooma.valid?(24, [:union, [:int, [:list, :string]]])
** (Protocol.UndefinedError) protocol Enumerable not implemented for 24. This protocol is implemented for: Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /root/deb/elixir_1.8.1-2/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /root/deb/elixir_1.8.1-2/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:3015: Enum.map_reduce/3
    (elixir) lib/enum.ex:2749: Enum.with_index/2
    (skooma) lib/skooma.ex:74: Skooma.validate_list/3
    (skooma) lib/skooma.ex:12: Skooma.valid?/3
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
```

**Comment by chanon** [comment]
Fixed it.

I have to say, I like this library's approach best compared to other similar libraries, so thank you!

**Comment by bobfp** [comment]
@chanon Thank you very much!
