### ISSUE TITLE
Error for implement on Struct

### ISSUE THREAD

**Issue by Tsugami** [bobfp/skooma#16]
Hi, I'm a newbie in elixir and I'm having trouble using your library. I can't implement on [Embed Struct](https://github.com/cronokirby/alchemy/blob/master/lib/Structs/Messages/Embed/embed.ex) of [Alchemy](https://github.com/cronokirby/alchemy)

       
My Code:
[`test/utils/embed_validator_test.exs:8`](https://github.com/Tsugami/hmmm/blob/master/test/utils/embed_validator_test.exs#L8)
[`ib/utils/embed_validator.ex:5`](https://github.com/Tsugami/hmmm/blob/master/lib/utils/embed_validator.ex#L5)

Error:
```error
  1) test should return the embed when is empty (ElixirTest.Utils.EmbedValidatorTest)
     test/utils/embed_validator_test.exs:8
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for %Alchemy.Embed{author: nil, color: nil, description: nil, fields: [], footer: nil, image: nil, provider: nil, thumbnail: nil, timestamp: nil, title: nil, type: nil, url: nil, video: nil} of type Alchemy.Embed (a struct). This protocol is implemented for the following type(s): Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream    
     code: assert EmbedValidator.valid?(embed) == embed
     stacktrace:
       (elixir 1.11.4) lib/enum.ex:1: Enumerable.impl_for!/1       
       (elixir 1.11.4) lib/enum.ex:141: Enumerable.reduce/3        
       (elixir 1.11.4) lib/enum.ex:3473: Enum.map/2
       (skooma 0.2.0) lib/map.ex:37: Skooma.Map.value_handler/3    
       (skooma 0.2.0) lib/map.ex:8: Skooma.Map.validate_map/3      
       (skooma 0.2.0) lib/skooma.ex:11: Skooma.valid?/3
       (my_elixir 0.1.0) lib/utils/embed_validator.ex:5: MyElixir.Utils.EmbedValidator.valid?/1
       test/utils/embed_validator_test.exs:10: (test)
     
 ```
 
 Tested with a normal Map and works

**Comment by Tsugami** [comment]
Hi, I convert the struct to map with `Map.from_struct` and it worked!
